apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
patches:
  - path: todo-app-backup-serviceaccount.yaml
  - path: todo-app-postgres-backup-cronjob.yaml
namePrefix: prod-
namespace: project-prod
