apiVersion: v1
kind: Pod
metadata:
  name: my-alpine
  labels:
    app: my-alpine
spec:
  containers:
  - image: alpine/curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always