###
GET http://localhost:3000/api/todos/

###
POST http://localhost:3000/api/todos/
content-type: application/json

{
  "content": "move to bermuda"
}

###
PUT http://localhost:3000/api/todos/4
content-type: application/json

{
  "id": 4,
  "content": "huf",
  "done": true
}