apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./todo-app-postgres-db.yaml
- ./todo-app-backend-service.yaml
- ./todo-app-backend-deployment.yaml
- ./todo-app-pvc.yaml
- ./todo-app-service.yaml
- ./todo-app-deployment.yaml
- ./todo-app-random-wiki-cronjob.yaml
- ./todo-app-route.yaml
- ./todo-app-backend-route.yaml
- ./todo-app-gateway.yaml
images:
- name: todo-app
  newName: adamfarhadi/dwk-todo-app
  newTag: 01adacb3fe08430c8e0d3f8fb5c8477bfc8af726
- name: todo-app-backend
  newName: adamfarhadi/dwk-todo-app-backend
  newTag: 01adacb3fe08430c8e0d3f8fb5c8477bfc8af726
- name: todo-app-random-wiki
  newName: adamfarhadi/dwk-todo-app-random-wiki
  newTag: 01adacb3fe08430c8e0d3f8fb5c8477bfc8af726
vars:
- fieldref:
    fieldPath: metadata.name
  name: POSTGRES_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: todo-app-postgres-svc
replacements:
- source:
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: Gateway
    name: todo-app-gateway
    fieldPath: metadata.name
  targets:
  - select:
      kind: HTTPRoute
      name: todo-app-route
    fieldPaths:
    - spec.parentRefs.0.name
  - select:
      kind: HTTPRoute
      name: todo-app-backend-route
    fieldPaths:
    - spec.parentRefs.0.name
- source:
    apiVersion: v1
    kind: Service
    name: todo-app-svc
    fieldPath: metadata.name
  targets:
  - select:
      kind: HTTPRoute
      name: todo-app-route
    fieldPaths:
    - spec.rules.0.backendRefs.0.name
- source:
    apiVersion: v1
    kind: Service
    name: todo-app-backend-svc
    fieldPath: metadata.name
  targets:
  - select:
      kind: HTTPRoute
      name: todo-app-backend-route
    fieldPaths:
    - spec.rules.0.backendRefs.0.name
