apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./todo-app-postgres-db.yaml
- ./todo-app-backend-service.yaml
- ./todo-app-backend-deployment.yaml
- ./todo-app-pvc.yaml
- ./todo-app-service.yaml
- ./todo-app-deployment.yaml
- ./todo-app-random-wiki-cronjob.yaml
- ./todo-app-route.yaml
- ./todo-app-backend-route.yaml
- ./todo-app-gateway.yaml
images:
- name: todo-app
  newName: adamfarhadi/dwk-todo-app
  newTag: 470a5cd3ec65fa2252d8224738253de470ea3da1
- name: todo-app-backend
  newName: adamfarhadi/dwk-todo-app-backend
  newTag: 470a5cd3ec65fa2252d8224738253de470ea3da1
- name: todo-app-random-wiki
  newName: adamfarhadi/dwk-todo-app-random-wiki
  newTag: 470a5cd3ec65fa2252d8224738253de470ea3da1
vars:
- name: POSTGRES_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: todo-app-postgres-svc
  fieldref:
    fieldpath: metadata.name
