apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./todo-app-postgres-db.yaml
- ./todo-app-backend-service.yaml
- ./todo-app-backend-deployment.yaml
- ./todo-app-pvc.yaml
- ./todo-app-service.yaml
- ./todo-app-deployment.yaml
- ./todo-app-random-wiki-cronjob.yaml
- ./todo-app-route.yaml
- ./todo-app-backend-route.yaml
- ./todo-app-gateway.yaml
images:
- name: todo-app
  newName: adamfarhadi/dwk-todo-app
  newTag: ec906b22b200c70e80d55604114bf8f64f663ca4
- name: todo-app-backend
  newName: adamfarhadi/dwk-todo-app-backend
  newTag: ec906b22b200c70e80d55604114bf8f64f663ca4
- name: todo-app-random-wiki
  newName: adamfarhadi/dwk-todo-app-random-wiki
  newTag: ec906b22b200c70e80d55604114bf8f64f663ca4
vars:
- fieldref:
    fieldPath: metadata.name
  name: POSTGRES_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: todo-app-postgres-svc
- fieldref:
    fieldPath: metadata.name
  name: TODO_APP_GATEWAY_NAME
  objref:
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: Gateway
    name: todo-app-gateway
- fieldref:
    fieldPath: metadata.name
  name: TODO_APP_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: todo-app-svc
- fieldref:
    fieldPath: metadata.name
  name: TODO_APP_BACKEND_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: todo-app-backend-svc
